// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var $$Array = require("bs-platform/lib/js/array.js");
var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");

var component = ReasonReact.statelessComponent("App");

function make(_children) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (_self) {
              return React.createElement("div", {
                          className: "container"
                        }, React.createElement("h1", {
                              className: "header"
                            }, "COMPUTERS TRIVIA"), React.createElement("div", {
                              className: "content"
                            }, React.createElement("h2", {
                                  className: "question"
                                }, "Which company was established on April 1st, 1976 by Steve Jobs, Steve Wozniak and Ronald Wayne?"), React.createElement("div", {
                                  className: "answersContainer"
                                }, $$Array.of_list(List.map((function (answer) {
                                            return React.createElement("button", {
                                                        className: "answerButton"
                                                      }, answer);
                                          }), /* :: */[
                                          "Microsoft",
                                          /* :: */[
                                            "Atari",
                                            /* :: */[
                                              "Apple",
                                              /* :: */[
                                                "Commodore",
                                                /* [] */0
                                              ]
                                            ]
                                          ]
                                        ])))));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.component = component;
exports.make = make;
/* component Not a pure module */
